### ISSUE TITLE
Tracking of dependencies for version 1.6.49

### ISSUE THREAD

**Issue by BrentonEarl** [BrentonEarl/w3af-sbo#1]
##### Dependencies
If it is checked off it is in the repo, up to date, and working with w3af.
- [ ] pip 7.1.2
- [ ] GitPython 1.0.1
- [ ] PyGithub 1.25.2
- [ ] ndg_httpsclient 0.4.0
- [ ] pyOpenSSL 0.15.1
- [ ] python-chardet 2.3.0
- [ ] guess-language 0.2
- [ ] python-cluster 1.1.1b3
- [ ] msgpack-python 0.4.6
- [ ] Markdown 2.6.1
- [ ] pyasn1 0.1.8
- [ ] lxml 3.4.4 (with BeautifulSoup 3.2.1 as depend)
- [ ] nltk 3.1 (with pysetuptools 18.2 as depend)
- [ ] graphviz 2.38.0
- [ ] gtksourceview 2.10.5
- [ ] pywebkitgtk 1.1.8
- [ ] scapy 2.0.1
- [ ] pybloomfiltermmap
- [ ] python-clamd
- [ ] python-esmre
- [ ] python-futures
- [ ] python-pdfminer
- [ ] python-phply
- [ ] python-stopit
- [ ] python-tblib
- [ ] python-ntlm
- [ ] python-halberd
- [ ] darts-util-lru
- [ ] Jinja2
- [ ] python-vulndb

**Comment by BrentonEarl** [comment]
Ignore issue references.  They were merged from a different repository.  Scapy has been submitted by the maintainer to be updated to version 2.3.1.

**Comment by BrentonEarl** [comment]
All packages are building with w3af 1.6.49 using slackrepo.  A small modification of w3af.SlackBuild is needed for it to build with slackrepo.  Change line 44 from this:
```bash
tar xvf $CWD/$VERSION.tar.gz -C $PKG/opt # Install to /opt
```
to this:
```bash
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz -C $PKG/opt # Install to /opt
```
I believe this is a bug in how slackrepo downloads and renames source files for consistency.  Manually building w3af works with the original string.

__Next step is to test w3af.__

**Comment by BrentonEarl** [comment]
Here is the slackrepo configuration file to use this git repository with slackrepo for testing purposes.  Rename it to slackrepo_w3af-sbo.conf and put it in /etc/slackrepo.  Download it here:  [slackrepo_w3af-sbo.conf.txt](https://github.com/BrentonEarl/w3af-sbo/files/37577/slackrepo_w3af-sbo.conf.txt)

For hint files, just copy /etc/slackrepo/SBo to w3af-sbo/.
```bash
cp -R /etc/slackrepo/SBo /etc/slackrepo/w3af-sbo/
```

**Comment by BrentonEarl** [comment]
Be sure to update this ticket:  https://github.com/andresriancho/w3af/issues/13037 after testing w3af with newer library versions.

**Comment by BrentonEarl** [comment]
Dependency tree for completeness:
```bash
network/w3af (update for git 678d956+dirty)
  python/stopit (ok)
    python/pysetuptools (ok)
  python/python-vulndb (ok)
    python/pysetuptools (ok)
  python/python-pdfminer (ok)
  python/python-futures (ok)
  python/python-esmre (ok)
    python/pysetuptools (ok)
  python/python-cluster (ok)
  python/python-clamd (ok)
    system/clamav (ok)
    python/pysetuptools (ok)
  python/python-chardet (ok)
    python/pysetuptools (ok)
  python/pyasn1 (ok)
  python/pyOpenSSL (ok)
    python/cryptography (ok)
      python/six (ok)
      python/pyasn1 (ok)
      libraries/enum34 (ok)
      libraries/cffi (ok)
        python/pysetuptools (ok)
        libraries/pycparser (ok)
  python/pip (ok)
    python/pysetuptools (ok)
  python/phply (ok)
    python/simplejson (ok)
    python/pysetuptools (ok)
    python/ply (ok)
  python/ndg_httpsclient (ok)
    python/pyOpenSSL (ok)
      python/cryptography (ok)
        python/six (ok)
        python/pyasn1 (ok)
        libraries/enum34 (ok)
        libraries/cffi (ok)
          python/pysetuptools (ok)
          libraries/pycparser (ok)
  python/msgpack-python (ok)
    python/pysetuptools (ok)
  python/lxml (ok)
    libraries/BeautifulSoup (ok)
  python/halberd (ok)
  python/guess-language (ok)
  python/darts.util.lru (ok)
    python/pysetuptools (ok)
  python/PyGithub (ok)
    python/pysetuptools (ok)
  python/Markdown (ok)
  network/scapy (ok)
  libraries/smmap (ok)
    python/pysetuptools (ok)
  libraries/python-tblib (ok)
    python/six (ok)
    python/pysetuptools (ok)
  libraries/python-ntlm (ok)
    python/pysetuptools (ok)
  libraries/pybloomfiltermmap (ok)
    python/pysetuptools (ok)
  libraries/nltk (ok)
    python/pysetuptools (ok)
  libraries/Jinja2 (ok)
    python/MarkupSafe (ok)
      python/pysetuptools (ok)
  libraries/GitPython (ok)
    libraries/gitdb (ok)
      libraries/smmap (ok)
        python/pysetuptools (ok)
  libraries/BeautifulSoup (ok)
  graphics/graphviz (ok)
```

**Comment by BrentonEarl** [comment]
Looks like it will be another week before I can update w3af to 1.6.49 in official SBo.  Have some testing to do for mitmproxy because I will need to add mitmproxy + deps to SBO first.

Tracking mitmproxy in my main personal SBo repository here:  https://github.com/BrentonEarl/es1-slackware-stuff/issues/5

**Comment by BrentonEarl** [comment]
Issue is blocked until netlib dependency cryptography is updated.  netlib is a dependency of mitmproxy.

See:  https://github.com/BrentonEarl/es1-slackware-stuff/issues/6

**Comment by BrentonEarl** [comment]
Awaiting approval for netlib, pyperclip, python-pillow.  After that it's on to testing mitmproxy and w3af.

**Comment by BrentonEarl** [comment]
May need to update https://github.com/BrentonEarl/es1-slackware-stuff/issues/3 once all testing in complete.

**Comment by BrentonEarl** [comment]
mitmproxy and all deps are uploaded to SBo.  Will test mitmproxy this week and next week.

**Comment by BrentonEarl** [comment]
urwid has been downgraded to version 1.0.3 in Slackware 14.2 RC2.  According to the change logs:
> Sat Mar 26 23:20:34 UTC 2016
> [snip]
> l/urwid-1.0.3-x86_64-1.txz:  Upgraded.
>   Switch to version 1.0.3, since wicd has problems with newer versions.

Since mitmproxy requires newer versions of urwid, I would have to revert to an older version of mitmproxy that is compatible with an older than 1.6.49 w3af release.  I am not sure what the point is in running mitmproxy and w3af on outdated releases.

Updating w3af looks to be stalled until the day comes that urwid is updated to a higher version (urwid > 1.3.0).  Anything other than that introduces too many regressions in w3af dependencies in SBo.

**Comment by BrentonEarl** [comment]
Bug that block an update to urwid 1.3.1+ in Slackware base.  https://bugs.launchpad.net/wicd/+bug/1429253
